/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollapseColumnItem: typeof import('./src/components/CollapseItem/CollapseColumnItem.vue')['default']
    CollapseItem: typeof import('./src/components/CollapseItem/CollapseItem.vue')['default']
    CollapseRowItem: typeof import('./src/components/CollapseItem/CollapseRowItem.vue')['default']
    CustomStatistic: typeof import('./src/components/CustomStatistic.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    'IEpIcon-': typeof import('~icons/ep/icon-')['default']
    IEpIconQuestionFilled: typeof import('~icons/ep/icon-question-filled')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpQuestionFIlled: typeof import('~icons/ep/question-f-illed')['default']
    IEpSwitch: typeof import('~icons/ep/switch')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
